### ISSUE TITLE
Error when installing on kali-linux

### ISSUE THREAD

**Issue by henmaster** [openai/openai-python#100]
For some reason I'm getting a build error when pip installing on Kali Linux. Correct me if I'm wrong, but I assume this is a build error. Attached is the output from my build.
[txt.log](https://github.com/openai/openai-python/files/8904264/txt.log)

**Comment by hallacy** [comment]
Hi @henmaster, thanks for the issue.

I _think_ this is related to [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1010284) report filed a couple of months ago. It seems to effect a lot of normal python installations. I think there's a solution at the end of the thread that might help?

I'll leave this issue open for a few days.  Since I don't think this is an issue with our library, I'll close it later this week unless I hear that this didn't solve your problem

**Comment by tronving** [comment]
> Hi @henmaster, thanks for the issue.
> 
> I _think_ this is related to [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1010284) report filed a couple of months ago. It seems to effect a lot of normal python installations. I think there's a solution at the end of the thread that might help?
> 
> I'll leave this issue open for a few days.  Since I don't think this is an issue with our library, I'll close it later this week unless I hear that this didn't solve your problem 

I think you were correct, I ended up fixing the problem by cloning from the source, than running the setup.py from there. Thanks for your quick response 😁

**Comment by hallacy** [comment]
I'm gonna close this for now then since it seems like this was resolved
