### ISSUE TITLE
ImportError: cannot import name 'OpenAI' from 'openai'

### ISSUE THREAD

**Issue by jdragonx** [openai/openai-python#1069]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Exactly this:

```
ImportError: cannot import name 'OpenAI' from 'openai'
```

Seems like is just a silly mistake that you didn't notice you had removed such an important part of the package, I had to pin my version to 1.7.1 to avoid this.

### To Reproduce

Just update to the latest version (1.7.2) and then try to import using the examples described in the documentation.

### OS

Ubuntu

### Python version

Python v3.10.12

### Library version

openai v1.7.2

**Comment by rattrayalex** [comment]
Hmm, I can't reproduce this:

```py
Python 3.9.18 (main, Oct  2 2023, 20:16:14) 
[Clang 16.0.3 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import openai
>>> openai.version.VERSION
'1.7.2'
>>> from openai import OpenAI
>>> OpenAI
<class 'openai.OpenAI'>
```

Can you try reinstalling 1.7.2 and try again? If you run into an error again, can you share your code and the full traceback?

**Comment by Domxnvk** [comment]
I am having the same issue on `1.9.0`. The import is simply not existing:

![image](https://github.com/openai/openai-python/assets/64827994/e560ae1e-76e1-4eaf-a999-d7da105d925d)

**Comment by mepc36** [comment]
I had the same problem as OP. It turned out to be a problem with my own management of python version and packages.

When I checked the version of `openai` with [this command](https://stackoverflow.com/a/20180597), I was on a very, very old version. I was on `0.23`. I was also running 2 different versions of python: 3.10.8 when I checked the version of `which python3`, but 3.10.6 when I checked the version of `which python`. This is just another reminder to be very careful when managing multiple versions of techs!

Here is how you fix the problem:
1. Uninstall all versions of openai:

```
python3 -m pip uninstall openai
```

Docs on `pip uninstall` command:
https://pip.pypa.io/en/stable/cli/pip_uninstall/

2. Install the latest version of openai:

```
python3 -m pip install openai==1.23.6
```

**Always** make sure you append the `python3 -m pip ...` prefix. This will prevent you from installing packages on versions of python that you aren't actually usually. 

Also, it's **usually** a good idea to peg your version number, just to make the debugging process easier.

Check here for the latest version:
https://github.com/openai/openai-python/releases

If you want a more global, automated solution, try running this code inside a conda env:
https://conda.io/projects/conda/en/latest/user-guide/getting-started.html
