### ISSUE TITLE
Add support for locally hosted img urls

### ISSUE THREAD

**Issue by Marcus-Peterson** [openai/openai-python#1110]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [ ] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

You know what I don't like doing right now. Creating a microservice and deploying it just to handle, serve and store img urls. 
OpenAi should implement a feature which allows the OpenAi vision API to be able to communicate with localhost. I know that this could be a complex task, but you guys have 100 of billions of dollar in funding. You guys could probably figure it out

### Additional context

I know that we can use bas64 encoding, but it's slow.

**Comment by rattrayalex** [comment]
Sorry, can you say more about the use-case? What code are you trying to write?

**Comment by Marcus-Peterson** [comment]
Well, it can be applied anywhere. Where vision is needed, this is what OpenAi have stated in the docs:
`For long running conversations, we suggest passing images via URL's instead of base64.`

**Comment by antont** [comment]
Can the files API be used for this?

It's not possible for OpenAI to fetch something from localhost URLs the normal way, by opening connections from there. It might be possible to have some sort of data service as a part of the client library, so that an open connection from your client would also work to serve files for GPT to access upon request, but that would be quite awkward and hard I imagine.

The files API looks like a good fit, as it's for uploading files to OpenAI so that your sessions can use them, without you needing a separate hosting provider. I don't know if it works for what you want though.

https://platform.openai.com/docs/api-reference/files

**Comment by Marcus-Peterson** [comment]
> Can the files API be used for this?
> 
> It's not possible for OpenAI to fetch something from localhost URLs the normal way, by opening connections from there. It might be possible to have some sort of data service as a part of the client library, so that an open connection from your client would also work to serve files for GPT to access upon request, but that would be quite awkward and hard I imagine.
> 
> The files API looks like a good fit, as it's for uploading files to OpenAI so that your sessions can use them, without you needing a separate hosting provider. I don't know if it works for what you want though.
> 
> https://platform.openai.com/docs/api-reference/files

Interesting, I read the docs briefly, I'll have to test this endpoint to see if it would work in my use case. Thanks for providing this, I should have realized that OpenAi would have something like this (Endpoints for handling files etc)
