### ISSUE TITLE
Can we get the response headers within a completion?

### ISSUE THREAD

**Issue by chitalian** [openai/openai-python#1175]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

There is a lot of useful information within the response headers. Can we add this to the ChatCompletion object that `client.chat.completions.create` makes?

<img width="695" alt="image" src="https://github.com/openai/openai-python/assets/26822232/317b9344-6031-4480-b1ab-48a4457807dc">

**Comment by rattrayalex** [comment]
This information can be accessed with the [raw response](https://github.com/openai/openai-python?tab=readme-ov-file#accessing-raw-response-data-eg-headers), like so:

```py
response = client.chat.completions.with_raw_response.create(params)
chat_completion = response.parse()
processing_ms = response.headers.get('openai-processing-ms')
```
we plan to add these properties directly to the response, so that in the future you'll be able to do, e.g., `response.processing_ms` or `response.ratelimit_rest_tokens` directly. 

We do not plan to add any headers to the chat completion object directly.

**Comment by chitalian** [comment]
This works! Thanks @rattrayalex
