### ISSUE TITLE
Fine tuning failure

### ISSUE THREAD

**Issue by AHPUymhd** [openai/openai-python#1207]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

An error occurred when I was fine-tuning a josn file to print the id of fine_tuning_job
![image](https://github.com/openai/openai-python/assets/72792297/d94ecf2b-974a-4941-b8c3-0230a1e23a98)
![image](https://github.com/openai/openai-python/assets/72792297/171a16b4-c3f5-4ce9-ba99-e5ad87a0d6c7)
![image](https://github.com/openai/openai-python/assets/72792297/708e63e6-8c93-4792-956b-c677498b2d87)
The returned model is none
May I ask what caused this error？
Thank you so much for your assistance.

### To Reproduce

As indicated above

### OS

Window 10

### Python version

Python 3.8.18

### Library version

openai 1.3.6

**Comment by rattrayalex** [comment]
This does not look like a bug in the SDK, so I'm going to go ahead and close this issue.

In this case, it looks like your problem is that you may need to top up your account, which you can do here: https://platform.openai.com/account/billing

For further assistance, please visit https://help.openai.com/
