### ISSUE TITLE
`CompletionUsage.generation` is `None` sometimes

### ISSUE THREAD

**Issue by stephantul** [openai/openai-python#1232]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

When getting a completion using `gpt-4-vision` the `generation` field of the `CompletionUsage` is sometimes `None`. I don't know when this happens exactly. This is not in accordance with the description or the `BaseModel`, which claims `generation` should always be `int`. 

Sorry if this is not a python issue.

### To Reproduce

Use `gpt-4-vision`, send an image. I'm not sure what the reason is.

### OS

macOS

### Python version

v3.10.8

### Library version

openai v1.3.6

**Comment by rattrayalex** [comment]
I don't believe there is a `generation` field – did you mean `completion_tokens`? There is a known bug in the API where that can be `null` sometimes, and that is being worked on.

Since this repo is only for issues with the Python SDK – and not the underlying API – I'm going to go ahead and close this issue.

**Comment by stephantul** [comment]
Yeah sorry, we call this `generation` internally, but I of course meant `completion_tokens`. Thanks for the quick response, sorry for posting it in the wrong place.
