### ISSUE TITLE
How are the text-search models {doc,query} different?

### ISSUE THREAD

**Issue by aurotripathy** [openai/openai-python#132]
Seems to me, these two models should be the same?
After all, its the same vector space.

```
text-search-ada-doc-001
text-search-ada-query-001
```
How would they be different to get a different nomenclature?

**Comment by hallacy** [comment]
Hi @aurotripathy, thanks for writing in.

Yep, you're totally correct: Same model. The model was designed to take in two different kinds of inputs as part of training. In order to make that a little more intuitive to users, we put out two interfaces to (hopefully) make the model easier to use.  Does that answer the question?

**Comment by aurotripathy** [comment]
@hallacy , thanks. That answers my question.
