### ISSUE TITLE
`_strict_response_validation` deprecation and Azure content filters

### ISSUE THREAD

**Issue by danilopeixoto** [openai/openai-python#1583]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

If `_strict_response_validation` may be deprecated, will the fixed behavior be set to `False`?

The Azure content filter annotation requires `object` attribute set to `""`. It relies on `_strict_response_validation=False`:

https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/content-filter?tabs=warning%2Cuser-prompt%2Cpython-new#annotations-and-sample-responses

### To Reproduce

1. Enable content filters in Azure OpenAI Service.
2. Stream chat completions with client:

```python
client = AzureOpenAI(
    azure_endpoint="<azure-endpoint>",
    azure_deployment="gpt-4-turbo",
    api_key="<api-key>",
    api_version="2024-02-01",
    _strict_response_validation=True # This will make strict validations and the request will fail.
)
```

Error:

```
Input should be 'chat.completion.chunk' [type=literal_error, input_value='', input_type=str]
```

### OS

Ubuntu 22.04

### Python version

v3.10.0

### Library version

v1.37.1

**Comment by RobertCraigie** [comment]
Yes if `_strict_response_validation` is removed, the fixed behaviour will be `_strict_response_validation=False`.

We also have no plans to support `_strict_response_validation=True` for the Azure client.

Out of curiosity are you using this flag in the standard client? We haven't heard of anyone actually enabling this behaviour yet.

---

also cc @kristapratico r.e. azure behaviour here, it's surprising that an empty string is returned in this case but I don't have full context, is this intentional?

**Comment by danilopeixoto** [comment]
> Out of curiosity are you using this flag in the standard client?

@RobertCraigie No. I have no application for `_strict_response_validation=True`.

**Comment by danilopeixoto** [comment]
@kristapratico Reference: https://github.com/mlflow/mlflow/issues/12767
