### ISSUE TITLE
Request for Endpoint to List All Threads

### ISSUE THREAD

**Issue by Kato-Official** [openai/openai-python#1660]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

Hey mate, hope all is well.

I would like to request the addition of an endpoint that allows for the retrieval of all threads. If there are concerns about potential security risks, such as team members or others within the same organization gaining access to all threads, I suggest implementing an additional layer of security. For example, you could restrict the listing of threads to those generated under a specific project and token bearer.

Additionally, I have noticed that this request has been reiterated multiple times since January but has not yet been addressed. Given the ongoing interest and potential impact of this feature, I believe it would be highly beneficial for many users.

This enhancement would significantly improve the usability and flexibility of the API, particularly for teams working on collaborative projects.

Thank you for considering this request. I look forward to your feedback.

Cheers

**Comment by RobertCraigie** [comment]
I'm going to close this as it's a request for a new API endpoint, not the Python SDK. I've forwarded this to the OpenAI team.

**Comment by johnkord** [comment]
@RobertCraigie Is there a plan to eventually support this endpoint by the API team? The metadata fields feel pointless if we can't search for them. It essentially requires a user of the Assistants API to store the Thread ID if it needs to look it up later (instead of being able to query for all Threads that match some metadata key/value). Another approach to solve this problem would be if we could choose the Thread ID when we create the thread (and thus, a user could hash some key/values -> thread ID). I'd much prefer querying for Threads within the context of an Assistant based on metadata key/values.
