### ISSUE TITLE
Limits argument can never get passed down?

### ISSUE THREAD

**Issue by dmakhervaks** [openai/openai-python#1790]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

It seems as though when initializing an openAI client like so:

since you cannot pass in the limits argument as a parameter, it will always default to the DEFAULT value here:

https://github.com/openai/openai-python/blob/aa6818997468b753546d55365d8142e2bb1c6640/src/openai/_base_client.py#L1127

openai.AsyncClient(())

### To Reproduce

1. Initialize an openai client like so: openai.AsyncClient(())
2. Try to pass in 'limits' argument or modify the 'http_client' to have custom Limits. 
3. This will not actually be propagated 

### Code snippets

```Python
openai.AsyncClient(())
```

### OS

linux

### Python version

3.9.12 

### Library version

1.50.0

**Comment by RobertCraigie** [comment]
> modify the 'http_client' to have custom Limits.

I cannot reproduce this part, passing in a custom HTTP client with different limits does get propagated
```py
import httpx
from openai import AsyncOpenAI

client = AsyncOpenAI(
    http_client=httpx.AsyncClient(
        limits=httpx.Limits(
            max_connections=1,
        )
    )
)
print(client._client._transport._pool._max_connections)
```
This prints `1` for me. Is it different for you?

---
Separately it is intentional that you can't pass `limits` directly to `OpenAI()`, the code you linked to is left-over from the original implementation and we haven't removed that yet.

The intended path for customizing limits is by [passing your own HTTP client instance](https://github.com/openai/openai-python?tab=readme-ov-file#configuring-the-http-client) directly.

**Comment by ganeshhnalla** [comment]
You have set the max_connections to 1, meaning the `httpx.AsyncClient` should only allow a maximum of 1 concurrent connection at a time.

```py
import httpx
from openai import AsyncOpenAI

http_client = httpx.AsyncClient(
    limits=httpx.Limits(
        max_connections=1,  # Set max connections to 1 (or any number you want)
    )
)

client = AsyncOpenAI(http_client=http_client)

print(client._client._transport._pool._max_connections)
```

The output is 
`1`
For me as well

**Comment by RobertCraigie** [comment]
Please re-open if you're still running into this issue.
