### ISSUE TITLE
No clear information or method to retrieve Usage.

### ISSUE THREAD

**Issue by raiyanyahya** [openai/openai-python#223]
### Describe the bug

Hi Team,

It seems that there is no way to get usage / quota information when using the api. I am not sure if this feature exists.
Was this available in earlier versions ? I am using openai==0.26.5
 

### To Reproduce

1. Try to fetch the usage of an organization.

### OS

ubuntu

### Python version

Python 3.8.10

### Library version

openai==0.26.5

**Comment by hallacy** [comment]
Hi @raiyanyahya, great question.
 
That is correct. There is currently no endpoint that will show usage information (except what is already returned in completion responses). 

Since this is an API question (and less a python specific question), please feel free to contact our support team at help.openai.com.
