### ISSUE TITLE
logprobs exposed in chat completion endpoint

### ISSUE THREAD

**Issue by whitead** [openai/openai-python#248]
### Describe the feature or improvement you're requesting

We found it useful to have `logprobs` for completions to evaluate confidence. We would like to have access to this attribute in the new chat completion endpoint. Thank you!

**Comment by sheikheddy** [comment]
I was looking into this since opening https://github.com/openai/openai-python/issues/245. 

This is due to a limitation in Whisper. I skimmed through https://github.com/openai/whisper/blob/7858aa9c08d98f75575035ecd6481f462d66ca27/whisper/decoding.py#L110 and the good news is that it doesn't seem like it would be that hard to change. Key line of code is this:

`logprobs = F.log_softmax(logits.float(), dim=-1)`

The main modification you'd need to do would be adding token probabilities to https://github.com/openai/whisper/blob/7858aa9c08d98f75575035ecd6481f462d66ca27/whisper/transcribe.py#L23 where currently only avg_logprob is included.

**Comment by primeviking** [comment]
^ this!

**Comment by logankilpatrick** [comment]
Hey folks, we are aware people are asking for this, no direct timeline for it but something we are keeping in mind.

**Comment by logankilpatrick** [comment]
If this is something you are looking for, please drop a 👍 above so the team can get a sense of demand.

**Comment by logankilpatrick** [comment]
I am going to close for now since this repo is for the Python SDK not API feedback but will follow up if we end up adding this.

**Comment by pradeepdev-1995** [comment]
@tiangolo any update on this?
still i am getting the error 
```openai.error.InvalidRequestError: Unrecognized request argument supplied: logprobs```
when trying to configure ```logprobs = 0``` in ```openai.ChatCompletion.create```

code i tried

```
completion = openai.ChatCompletion.create(
            engine="model_name",
            temperature=0.2,
            messages=[{"role": "user", "content": prompt}],
            logprobs = 0
        )

```
