### ISSUE TITLE
no response from embedding api for 600s

### ISSUE THREAD

**Issue by lewiswilliam** [openai/openai-python#392]
### Describe the bug

This maybe true for other openai python api's as well. We are using openai api's via the python library in a multi threaded application which is always ON, i.e. we do not frequently start/restart the application.

Following is the code:
```
from embeddings_utils import get_embedding
input = get_embedding("this is a test", engine="text-embedding-ada-002")
```
When there is a long period of inactivity, intermittently, we get responses for above after 600s. This problem some time resolves itself after some requests/time. But during the time it gives issue, response is received after exact 600-601 seconds. It looks like request goes and there is no response for 600s and then it retries and that works immediately.

Any idea about this issue?

### To Reproduce

No particular steps, please see description above.

### OS

Linux/Ubuntu

### Python version

Python v3.7.5

### Library version

open-ai 0.27.2

**Comment by tuliren** [comment]
600 second is the default timeout setting:

https://github.com/openai/openai-python/blob/794def37e51f9dbfd1fef7cd451a5d92d5323a43/openai/api_requestor.py#L34

Not sure about the root cause, but you can make it timeout and retry faster by passing in a shorter `request_timeout` parameter. This parameter is not supported by the `get_embedding` function currently, but you can replace it with the underlying code:

https://github.com/openai/openai-python/blob/794def37e51f9dbfd1fef7cd451a5d92d5323a43/openai/embeddings_utils.py#L18-L23

**Comment by lewiswilliam** [comment]
Hi @tuliren 

Thanks for your response.

That is exactly what we have done for now, used `request_timeout`

Just added this bug here so that its fixed whenever possible.

**Comment by tuliren** [comment]
By the way, you can pass in `request_timeout` to the `get_embedding` function directly now.

**Comment by rattrayalex** [comment]
Closing as stale.
