### ISSUE TITLE
error_data is 'Not Found'

### ISSUE THREAD

**Issue by 3293406747** [openai/openai-python#413]
### Describe the bug

when I run this script,it make mistake, AttributeError: 'str' object has no attribute 'get'
then I debug this script and find that error_data is 'Not Found'

![image](https://user-images.githubusercontent.com/98522540/233877518-a316639a-334a-4194-834c-39942be9dc2c.png)

![image](https://user-images.githubusercontent.com/98522540/233878008-928eb1b5-6c39-4e57-b724-a65a87825906.png)

![image](https://user-images.githubusercontent.com/98522540/233877128-16bd024d-b243-434f-8680-e52c8900d8cb.png)

### To Reproduce

1. update 'api_requestor.py' file,add lines in request_raw function: 
```python       
proxy = {
            'http': '127.0.0.1:7890',
            'https': '127.0.0.1:7890'
        }
# 7890 is my proxy port
```
3. update 'proxies=_thread_context.session.proxies' to proxies=proxy
4. run it in main program:
```python
import openai

openai.api_key = "my openai key"
openai.api_base = "https://api.openai-proxy.com"

# list models
models = openai.Model.list()

# print the first model's id
print(models.data[0].id)

# create a completion
completion = openai.Completion.create(model="ada", prompt="Hello world")

# print the completion
print(completion.choices[0].text)
```

### OS

windows

### Python version

Python v3.10.0

### Library version

openai-poython v0.27.4

**Comment by codal-smit** [comment]
Can I pick this issue?

**Comment by cyborg7898** [comment]
Can I pick this issue?

**Comment by 3293406747** [comment]
Sorry,I can't understand the meaning about pick the issue.Can you expain it for me?

**Comment by cyborg7898** [comment]
I can work on this issue.

**Comment by 3293406747** [comment]
I'm so happy hearing that.Next, how to solve this issue?

**Comment by codal-smit** [comment]
> I'm so happy hearing that.Next, how to solve this issue?

It's happening because of different error response format from server side. Just wondering should we handle this via code or fix response from server. 

Error response is look like this
`{'timestamp': '2023-04-29T04:31:07.541+00:00', 'status': 404, 'error': 'Not Found', 'message': '', 'path': '/models'}`
But code expecting some like this
`{'error': {'message': 'Invalid URL (GET /v1/chat/completions/models)', 'type': 'invalid_request_error', 'param': None, 'code': None}}`

**Comment by cyborg7898** [comment]
> I'm so happy hearing that.Next, how to solve this issue?

> I'm so happy hearing that.Next, how to solve this issue?

It's happening because of different error response format from server side. Just wondering should we handle this via code or fix response from server. 

Error response is look like this
`{'timestamp': '2023-04-29T04:31:07.541+00:00', 'status': 404, 'error': 'Not Found', 'message': '', 'path': '/models'}`
But code expecting some like this
`{'error': {'message': 'Invalid URL (GET /v1/chat/completions/models)', 'type': 'invalid_request_error', 'param': None, 'code': None}}`

**Comment by 3293406747** [comment]
Actually，err_data = resp["error"].
So，code expecting should like this.

```python
{
	'timestamp': '2023-04-30T10:41:32.842+00:00',
	'status': 404,
	'error': {
		'message': 'Invalid URL (GET /v1/chat/completions/models)',
		'type': 'invalid_request_error',
		'param': None,
		'code': None
	},
	'message': '',
	'path': '/models'
}
 ```

I know that it's happening because of different error response format from server side.
But I still don't know that what is err_data and how to work on the issue.

**Comment by imaffe** [comment]
I think the first improvement could be change the client side code and print out the original error message. Is there a working PR on this one ? If not I can pick up this one.

**Comment by 3293406747** [comment]
> I think the first improvement could be change the client side code and print out the original error message. Is there a working PR on this one ? If not I can pick up this one.

what is PR？

**Comment by c7785812** [comment]
> Actually，err_data = resp["error"]. So，code expecting should like this.
> 
> ```python
> {
> 	'timestamp': '2023-04-30T10:41:32.842+00:00',
> 	'status': 404,
> 	'error': {
> 		'message': 'Invalid URL (GET /v1/chat/completions/models)',
> 		'type': 'invalid_request_error',
> 		'param': None,
> 		'code': None
> 	},
> 	'message': '',
> 	'path': '/models'
> }
> ```
> 
> I know that it's happening because of different error response format from server side. But I still don't know that what is err_data and how to work on the issue.

您好，请问有解决方案了吗，谢谢
