### ISSUE TITLE
`get_embedding` does not update.

### ISSUE THREAD

**Issue by syker-uk** [openai/openai-python#422]
### Describe the bug

I've noticed that using `get_embedding` repeatedly does not actually embeds the tokens but returns the previous result. Side by side comparison of `from openai.embeddings_utils import get_embedding` and `tiktoken` with just a length check:
```
Generating Text.
1536 1320
1536 1707
1536 1986
1536 1901
1536 2239
1536 2429
1536 2406
1536 2364
Final Length: 1328 (which is normal)
```

### To Reproduce

It should be simple enough to count tokens for different files with both `get_embedding` and `tiktoken`.

### OS

macOs

### Python version

Python 3

### Library version

openai-python

**Comment by EliahKagan** [comment]
It is expected that all embeddings from the same model have the same length.

The length of an embedding is the number of coordinates it has, which is the dimension of the vector space it is in. This is different for different embedding models, but it is guaranteed never to depend on *what* text is embedded.

The [recommended](https://platform.openai.com/docs/guides/embeddings/second-generation-models) and most popular OpenAI embedding model, [text-embedding-ada-002](https://openai.com/blog/new-and-improved-embedding-model), embeds texts in a 1536-dimensional vector space. As such, the length of any vector returned by that model is always 1536, regardless of the length or content of the text that was embedded to produce it. So if the left column of your table is produced by calling `len` on return values of `get_embedding`, then it doesn't indicate a problem.

Equality comparison should show that the embeddings are unequal. To check that different texts' embeddings are substantially different--rather than, for example, being unequal only due to rounding error--you can compute their [cosine similarities](https://platform.openai.com/docs/guides/embeddings/which-distance-function-should-i-use). The maximum possible cosine similarity is 1, which is the similarity between any embedding and itself.

---

To verify that text-embedding-ada-002 should produce 1536-dimensional vectors, see [output dimensions](https://platform.openai.com/docs/guides/embeddings/second-generation-models), as well as the example output in the [API reference](https://platform.openai.com/docs/api-reference/embeddings/create), which includes:

```json
      "embedding": [
        0.0023064255,
        -0.009327292,
        .... (1536 floats total for ada-002)
        -0.0028842222,
      ],
````
