### ISSUE TITLE
Invalid URL (POST /v1/engines/gpt-3.5-turbo/chat/completions)

### ISSUE THREAD

**Issue by wickeym** [openai/openai-python#531]
### Describe the bug

I am trying to use chat completions in python with this openai library, but keep hitting the same error.
I am using this documentation: [API Guides](https://platform.openai.com/docs/guides/gpt) and [API docs](https://platform.openai.com/docs/api-reference/chat/create?lang=python)

I see the url is different than the one listed in the API docs, so maybe there is an issue with this library?

Thank you,
Michael

### To Reproduce

```python
import openai
openai.api_key = os.environ["OPENAI_API_KEY"]
model_engine = "gpt-3.5-turbo" # Or gpt-4
response = openai.ChatCompletion.create(
    engine=model_engine,
    messages=[
        {"role": "system", "content":"<my setup message>"},
        {"role": "user", "content": "<my prompt>"}
    ],
    max_tokens=256,
    temperature=0,
)
```
Error:
```
openai.error.InvalidRequestError: Invalid URL (POST /v1/engines/gpt-3.5-turbo/chat/completions)
```

### OS

macOS

### Python version

Python v3.8.13

### Library version

openai-python v0.27.8

**Comment by EliahKagan** [comment]
The `engines` endpoint is [deprecated](https://help.openai.com/en/articles/6283125-what-happened-to-engines), and the `models` endpoint should be used instead. Pass the model name as a `model` argument, instead of as an `engine` argument:

```diff
-    engine=model_engine,
+    model=model_engine,
```

I've verified that the code you showed produces the error you showed, and that this change eliminates the error.

See [Deprecations](https://platform.openai.com/docs/deprecations/2022-06-03-legacy-endpoints) and [What happened to engines?](https://help.openai.com/en/articles/6283125-what-happened-to-engines) Unlike traditional completions, I don't believe chat completions have ever supported `engine`, only `model`. `model` can be used with both.

So I think the behavior you observed is not itself a bug in this library or the OpenAI API. However, if any current documentation continues to recommend the use of `engine`, I think that would be considered a bug in that documentation.

But I don't see a recommendation to use `engine`, or any mention of it, on the [API Guides](https://platform.openai.com/docs/guides/gpt) or [API docs](https://platform.openai.com/docs/api-reference/chat/create?lang=python) pages you linked to. [API Guides](https://platform.openai.com/docs/guides/gpt) shows this code:

```python
import openai

openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"},
        {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
        {"role": "user", "content": "Where was it played?"}
    ]
)
```

[API docs](https://platform.openai.com/docs/api-reference/chat/create?lang=python) shows this code:

```python
import os
import openai
openai.api_key = os.getenv("OPENAI_API_KEY")

completion = openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Hello!"}
  ]
)

print(completion.choices[0].message)
```

**Comment by wickeym** [comment]
Hi EliahKagan, I can't believe I overlooked that. I guess the bug was in my head. Thank you! :)
