### ISSUE TITLE
APIConnectionError: Error communicating with OpenAI

### ISSUE THREAD

**Issue by bramses** [openai/openai-python#56]
Running into certificate errors when trying to ping the API. Happens both in `virtualenv` and `regular` Python

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/openai/api_requestor.py", line 255, in request_raw
    result = _thread_context.session.request(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/engines (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "search.py", line 21, in <module>
    main()
  File "search.py", line 9, in main
    engines = openai.Engine.list()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/openai/api_resources/abstract/listable_api_resource.py", line 27, in list
    response, _, api_key = requestor.request(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/openai/api_requestor.py", line 98, in request
    result = self.request_raw(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/openai/api_requestor.py", line 265, in request_raw
    raise error.APIConnectionError("Error communicating with OpenAI") from e
openai.error.APIConnectionError: Error communicating with OpenAI
```

**Comment by hallacy** [comment]
Hello! Thank you for reaching out!

The CERTIFICATE_VERIFY_FAILED error might be caused by an outdated certifi package in Python. Here's a relevant discussion: https://stackoverflow.com/questions/51925384/unable-to-get-local-issuer-certificate-when-using-requests-in-python. Let me know if this doesn't help, and we'll keep troubleshooting.

**Comment by bramses** [comment]
Unfortunately the `--upgrade` flag seems to have been ineffective :(

```
(.venv) python % pip install --upgrade certifi
Requirement already satisfied: certifi in ./.venv/lib/python3.8/site-packages (2021.10.8)
```

I also ran the verification func from [certifi lib](https://pypi.org/project/certifi/) and got the expected path:

```
(.venv) python % python -m certifi            
~/code/.venv/lib/python3.8/site-packages/certifi/cacert.pem
```

**Comment by bramses** [comment]
I figured it out, my VPN was blocking external requests, for anyone who has a M1 Macbook in the future make sure your network calls aren't being tunneled by another app :)

**Comment by ElementQi** [comment]
> I figured it out, my VPN was blocking external requests, for anyone who has a M1 Macbook in the future make sure your network calls aren't being tunneled by another app :)

Same as win10. I figured out that just now by simply shutting down my clash terminal XD

**Comment by dsj96** [comment]
HI [ElementQi]
I have the same problem, Can you tell me how to shut down the clash terminal XD? Thanks.

**Comment by ElementQi** [comment]
You may misunderstand what am I talking about. XD is an emoji. You just need to shutdown your VPN services on your device. 哥，XD就是个表情，你把你电脑上的VPN全关了就行，开VPN有时候访问不了chatGPT

**Comment by ElementQi** [comment]
> HI [ElementQi] I have the same problem, Can you tell me how to shut down the clash terminal XD? Thanks.

You may misunderstand what am I talking about. XD is an emoji. You just need to shutdown your VPN services on your device. 哥，XD就是个表情，你把你电脑上的VPN全关了就行，开VPN有时候访问不了chatGPT

**Comment by dsj96** [comment]
haha

**Comment by TheKOG** [comment]
All methods above can not solve my problem , because I'm in China , where one can't connect to openai without VPN or Proxy.
For my Chinese compatriots following method works:
https://www.zhihu.com/question/587322263/answer/2919916984

**Comment by ElementQi** [comment]
> All methods above can not solve my problem , because I'm in China , where one can't connect to openai without VPN or Proxy. For my Chinese compatriots following method works: https://www.zhihu.com/question/587322263/answer/2919916984

I'm in China as well. One of my accounts is using a google account by implementing an Indian virtual phone number, and it works only when I don't use any proxies(As for website login, I need to use VPN to login google account and then close it to use the chatGPT interface). One of my friends' accounts is signed up with his qqmail and Indian phone number, which can only access openAI by using VPN. That's weird.

**Comment by TheKOG** [comment]
都是中国人拽啥洋文XD




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月3日(星期五) 晚上6:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [openai/openai-python] APIConnectionError: Error communicating with OpenAI (Issue #56)





  
All methods above can not solve my problem , because I'm in China , where one can't connect to openai without VPN or Proxy. For my Chinese compatriots following method works: https://www.zhihu.com/question/587322263/answer/2919916984
  
I'm in China as well. One of my accounts is using a google account by implementing an Indian virtual phone number, and it works only when I don't use any proxies(As for website login, I need to use VPN to login google account and then close it to use the chatGPT interface). One of my friends' accounts is signed up with his qqmail and Indian phone number, which can only access openAI by using VPN. That's weird.

**Comment by ElementQi** [comment]
写习惯了XD

**Comment by lavafool** [comment]
> All methods above can not solve my problem , because I'm in China , where one can't connect to openai without VPN or Proxy. For my Chinese compatriots following method works: https://www.zhihu.com/question/587322263/answer/2919916984

确实解决了，谢谢大佬！

**Comment by 1337235931** [comment]
> All methods above can not solve my problem , because I'm in China , where one can't connect to openai without VPN or Proxy. For my Chinese compatriots following method works: https://www.zhihu.com/question/587322263/answer/2919916984

您好，加上后又报另一个错误。这个有办法解决吗？
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A5B8C1CB88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))

**Comment by kfchandsome** [comment]
> 我也遇到这个问题，怎么解决，关闭VPN连接不上

**Comment by Cherub1Zhuang** [comment]
> 

关闭vpn就链接超时呀

**Comment by Crazy0Dave** [comment]
> > All methods above can not solve my problem , because I'm in China , where one can't connect to openai without VPN or Proxy. For my Chinese compatriots following method works: https://www.zhihu.com/question/587322263/answer/2919916984
> 
> 您好，加上后又报另一个错误。这个有办法解决吗？ openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A5B8C1CB88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))

确定代理ip和代理端口写的是自己挂的vpn的ip和端口

**Comment by 1337235931** [comment]
我已经把api接口调通了，解决了问题，但是，被封了，不知道因为什么，在网上有很多类似的。但是chatgpt还可以用，api禁止访问了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openai/openai-python"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月10日(星期五) 晚上7:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openai/openai-python] APIConnectionError: Error communicating with OpenAI (Issue #56)





   
All methods above can not solve my problem , because I'm in China , where one can't connect to openai without VPN or Proxy. For my Chinese compatriots following method works: https://www.zhihu.com/question/587322263/answer/2919916984
  
您好，加上后又报另一个错误。这个有办法解决吗？ openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A5B8C1CB88&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
  
确定代理ip和代理端口写的是自己挂的vpn的ip和端口

**Comment by kkptm** [comment]
我租用了一个美国服务器准备部署一个跳板，结构在服务器上就无法ping通api.openai.com

**Comment by kkptm** [comment]
在国内又搞了台服务器，在服务器上挂VPN又可以==！

**Comment by hackersong** [comment]
import openai
openai.organization="XXXX"
openai.api_key = "XXXX"
proxies = {
     'http': "http://xxxx:xxxx",
     'https': "http://xxxx:xxxx"}
 openai.proxy = proxies
openai.Model.list()
