### ISSUE TITLE
AzureOpenAI error :(

### ISSUE THREAD

**Issue by samedovzaur** [openai/openai-python#752]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

I'm getting this error:
ImportError: cannot import name 'AzureOpenAI' from 'openai' (/usr/local/lib/python3.10/dist-packages/openai/__init__.py)
 while import ing lbrary, 0.28.1 version of openai is being used.
Whay should i do?

### To Reproduce

1. imported library openai and AzureOpenAI
2. didn't run gave error.

### OS

macos

### Python version

3.10

### Library version

0.28.1

**Comment by RobertCraigie** [comment]
@samedovzaur This is happening because you're using the v0 of this library and looking at the docs for v1. The `AzureOpenAI` class was only added in v1.

If you install the latest version you can run `openai migrate` to automatically update your code.

Alternatively you can continue using the current version, see the README.md here: https://github.com/openai/openai-python/tree/284c1799070c723c6a553337134148a7ab088dd8?tab=readme-ov-file#microsoft-azure-endpoints

**Comment by samedovzaur** [comment]
> @samedovzaur This is happening because you're using the v0 of this library and looking at the docs for v1. The `AzureOpenAI` class was only added in v1.
> 
> If you install the latest version you can run `openai migrate` to automatically update your code.
> 
> Alternatively you can continue using the current version, see the README.md here: https://github.com/openai/openai-python/tree/284c1799070c723c6a553337134148a7ab088dd8?tab=readme-ov-file#microsoft-azure-endpoints

Will check it in a bit, Thank you for quick respond.
