### ISSUE TITLE
How do I know which account an OpenAI token is associated with ?

### ISSUE THREAD

**Issue by yilas** [openai/openai-python#936]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

Hello 👋🏻 

This isn't really a bug, but rather a question. I have several tokens to access OpenAI. I know how to find out whether they're valid or not, but I can't see how to find out which account is associated with them.

How can I get this information ? Does OpenAI Python API library support this ?

Thank you for your reply

**Comment by BlueHephaestus** [comment]
I've looked through all the [OpenAPI Spec and endpoints detailed](https://github.com/openai/openai-openapi/blob/master/openapi.yaml) and have not found any that provide information about the user making the request, nor am I seeing anything in the documentation. 

This is probably for security reasons and isn't intended to be a feature, but if it is they can tag this with the `enhancement` tag.

### Alternative Solution

That said, if your issue is just keeping track of which user has which API key on your machine, you can do this by setting them to differently named environment variables, like so:
```
export BLUE_OPENAI="sk-justkiddingnotgonnatypeinmyapikey"
export YILAS_OPENAI="sk-thisisanotherexampleofanapikey"
export RED_OPENAI="sk-waybetterthanbluesapikey"
```
And either putting that in your shell session or in your .bashrc, or adding it to environment variables using windows if you're using that. Then you could use it in your code like the following:
```python
import os
from openai import OpenAI

client = OpenAI(api_key=os.environ["BLUE_OPENAI"])

completion = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {
            "role": "user",
            "content": "My name is Blue",
        },
    ],
)
```
```python
import os
from openai import OpenAI

client = OpenAI(api_key=os.environ["RED_OPENAI"])

completion = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {
            "role": "user",
            "content": "My name is Red, i'm cooler than Blue",
        },
    ],
)
```
Best of luck in your projects!

**Comment by rattrayalex** [comment]
Thanks for the suggestion!

This sounds like a feature request for the underlying OpenAI API and not the Python library, so I'm going to go ahead and close this issue.

Would you mind reposting at [community.openai.com](https://community.openai.com)?
